### ISSUE TITLE
[Request] Set default build target

### ISSUE THREAD

**Issue by PeteCrighton** [idleberg/atom-build-sassc#1]
I always use the SassC (user) build target to use my non-default custom arguments (because I keep SCSS & CSS files in different folders). It is a bit inconvenient to have to choose that build target every time I open Atom (mostly because I keep forgetting).
Having an option to set a default build target (and being able to tweak that for different projects, ideally) would be a great addition, I think. Unless that’s already possible, then I’d appreciate a pointer in the right direction on how to do this.

**Comment by idleberg** [comment]
I don't think that the `build`plugin allows the definition of a default and I wouldn't want to change the default behaviour just because of a single request. However, I could add a keyboard shortcut for the user build target, would that help?

**Comment by PeteCrighton** [comment]
There is a rather old issue in noseglid/atom-build#427, so that seems to be the case. Not changing the default behaviour also makes sense.
But yeah, a configurable user build target keybinding could be useful.

**Comment by idleberg** [comment]
Actually, you can already assign your own keymap binding to the command. From the Atom menu, open *Keymap* add add something like the following:

```cson
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-u': 'sassc:compile-with-user-settings'
```

**Comment by PeteCrighton** [comment]
Good to know, thanks!

**Comment by PeteCrighton** [comment]
I don’t think `atom-workspace` is needed, by the way … although I am not quite sure what it does, but it surely works without it.
